### ISSUE TITLE
[Feature Request] Can we please have sound settings, to turn off sounds?

### ISSUE THREAD

**Issue by jeske** [TheGeneticsGuy/Guild-Roster-Manager#40]
Guild Roster Manager is great, but with the high churn on hardcore servers, the number of ding sounds is obnoxious. 

Can we get a sound-settings panel to turn off individual sounds... or even just a single checkbox to disable all event based sounds?

**Comment by TheGeneticsGuy** [comment]
Can you clarify exactly what sounds you'd like an option to disable? I don't actually play on Hardcore so I am not too familiar with all the dings. Are these thr ones when people hit max level and Blizz server wide announces?

**Comment by jeske** [comment]
No, not the server wide max level announce. That is from bliz and can be
turned off in bliz settings.

1. Guild member Dings level
2. Member Joined the guild

Both have additional chat lines and sounds created by GRM. It uses the ui
dialog close sound. It is very annoying on the high churn hard ore guilds.

**Comment by TheGeneticsGuy** [comment]
So, GRM doesn't really add sounds at all if someone joins or levels, so if it IS doing this then there is some kind of bug. I've never heard this sound at all, so might be a bug exclusive to classic.. I'll investigate it when I have some time. Preferably tonight because I go on vacation for the next 2 weeks tomorrow lol. Thanks for the report.

**Comment by TheGeneticsGuy** [comment]
Ooo just had a chance to login and ya, found the issue -- FriendsFrame was being forced to open/close in the background to force refresh of the guild data. This was due to an issue back when Classic for launched a while ago where GuildRoster() wasn't triggering properly so new joins member data would be nil when querying the server until you forced the frame to load. Blizz fixed that and this I guess has been hanging around there since then.

This shouldn't happen when someone levels, however. I am sitting in a 1000 member hardcore guild now just to test and I am only getting it when they join, not when they level. Is there possibly a different addon giving you sound when someone levels? Regardless, I gotta run again, but I'll revisit this and push out a fix before I am gone. And ya, someone just spammed invites to about 50 low levels and the sound spam was CRAZY!!! Surprised you are the first to report this!

**Comment by jeske** [comment]
It's possible I was mistaken and it's only happening when they join. In my guild both activities happen so much that I must have mistakenly thought it was for both.

Your explanation makes sense, as before filing this I looked through the GRM code trying to find a place that it played a sound and couldn't find one!

**Comment by TheGeneticsGuy** [comment]
Ok cool. I'll try to get something out tonight. I am in a hotel in Vancouver right now but the kids just went to sleep and I have a few minutes on my laptop. I am being reminded of how much it sucks to do any kind of coding on a laptop, especially since I didn't bring a mouse either lol.

**Comment by TheGeneticsGuy** [comment]
Ok, sorry it took me so long, got wife aggro. I gotta  crash now though lol -- Release is out here on github, I'll send it to Wago and curseforge as well but sometimes curse can take up to an hr to approve. Anyway, count this as resolved! Thanks again for the report! That would have driven me nuts as well! The discord channel linked here has a bugreports/suggestions section as well: https://discord.gg/UmN3YSQjpt   -- Obviously reports here are fine too.
