### ISSUE TITLE
Who Changed Note

### ISSUE THREAD

**Issue by Nuroduas** [TheGeneticsGuy/Guild-Roster-Manager#7]
With the feature that logs the note change is it possible to capture who made the note change?  We have had issues with members changing other members notes to something durogatory or offensive.  It would be helpful if this would show who changed the note.

**Comment by TheGeneticsGuy** [comment]
Unfortunately this is not possible because the server does not log who made the changes. I REALLY wish there was a solution to this, but there really isn't. It wasn't even until BFA that Blizz finally made it so people could only edit their own public note unless they were an officer. You are not alone in that being a major headache for years for guild leadership.

GRM does have a specific feature to attempt to somewhat address this, however, for Classic. Essentially what you can do is restrict editing the public note to just your officers. Then, if someone in chat types "!note theirNoteHere" - if there is an officer currently online with GRM installed, it will auto-set that player's public note for them. This can be useful if the guild is educated how to use it.

**Comment by Nuroduas** [comment]
Thank you for the reply.  For the feature in Classic is it just posting that in Guild Chat or do whisper the officer?

**Comment by TheGeneticsGuy** [comment]
Just posting in guild chat works. No need to whisper anyone. Try it out!
